CREATE DATABASE dentistas;
USE dentitas;

CREATE TABLE clientes(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
telefone VARCHAR(50) NOT NULL,
cpf VARCHAR(11) UNIQUE NOT NULL
);

CREATE TABLE agenda(
id INT AUTO_INCREMENT PRIMARY KEY,
data DATETIME
);

CREATE TABLE profissionais(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
experiencia VARCHAR(100) NOT NULL
);
